
package Project;


import javax.swing.JOptionPane;
/**
 *
 * @author Mehran & Mahboobeh
 */
public class LoginFrame extends javax.swing.JFrame {

    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginE = new javax.swing.JButton();
        userText = new javax.swing.JTextField();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        passField = new javax.swing.JPasswordField();
        loginC = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginE.setText("Login employee");
        loginE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginEActionPerformed(evt);
            }
        });
        getContentPane().add(loginE, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, -1, -1));
        getContentPane().add(userText, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 108, -1));

        label1.setText("Username");
        getContentPane().add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, -1, -1));

        label2.setText("Password");
        getContentPane().add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, -1, -1));
        getContentPane().add(passField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 110, -1));

        loginC.setText("Login customer");
        loginC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginCActionPerformed(evt);
            }
        });
        getContentPane().add(loginC, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginEActionPerformed
      boolean Aut;
             Aut = Access.logEmployee(userText.getText(),new String(passField.getPassword()));
                   if (Aut)
             {
                new DashBoard().setVisible(true);
                LoginFrame.this.dispose();
             }
      else
             { 
                JOptionPane.showMessageDialog(null, "WRONG USERNAME OR PASSWORD\n try again");
             }

        
            
    //        File file = new File("account.txt");
    //        StringBuffer contents = new StringBuffer();
    //        BufferedReader reader = null;
    //        try {
    //            reader = new BufferedReader(new FileReader(file));
    //            String text = null;
    // 
    //            // repeat until all lines is read
    //            text = reader.readLine(); 
    //            label2.setText(text);
    //            
    //        } 
    //        catch (FileNotFoundException e) {
//                        int n = JOptionPane.showConfirmDialog(
//    						null,
//    						"Are you sure you want to delete?",
//    						"Confirm File Delete",
//    						JOptionPane.YES_NO_OPTION);
    //        } catch (IOException e) {
    //            e.printStackTrace();
    //        }


    }//GEN-LAST:event_loginEActionPerformed

    private void loginCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginCActionPerformed
        // TODO add your handling code here:
        boolean Aut;
             Aut = Access.logCustomer(userText.getText(),new String(passField.getPassword()));
                   if (Aut)
             {
                new ClaimFrame().setVisible(true);
                LoginFrame.this.dispose();
             }
      else
             { 
                JOptionPane.showMessageDialog(null, "WRONG USERNAME OR PASSWORD\n try again");
             }


    }//GEN-LAST:event_loginCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                LoginFrame login=new LoginFrame();
                login.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Label label1;
    private java.awt.Label label2;
    private javax.swing.JButton loginC;
    private javax.swing.JButton loginE;
    public static javax.swing.JPasswordField passField;
    public static javax.swing.JTextField userText;
    // End of variables declaration//GEN-END:variables
}
